"""empty message

Revision ID: 317c53791294
Revises: 6b1658e36215
Create Date: 2022-04-07 11:59:22.947806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '317c53791294'
down_revision = '6b1658e36215'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
