"""empty message

Revision ID: 6e7c601c8ab9
Revises: 1d9183cd8cd8
Create Date: 2022-04-07 17:22:59.945002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e7c601c8ab9'
down_revision = '1d9183cd8cd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('valla', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('valla', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('valla', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('valla', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    # ### end Alembic commands ###
