"""empty message

Revision ID: 8612bece3fa7
Revises: ba44c60801df
Create Date: 2022-04-08 13:54:49.009501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8612bece3fa7'
down_revision = 'ba44c60801df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('order', sa.Column('created', sa.DateTime(), nullable=True))
    op.drop_column('order', 'register_date')
    op.add_column('owner', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('valla', sa.Column('format', sa.String(length=20), nullable=False))
    op.add_column('valla', sa.Column('created', sa.DateTime(), nullable=True))
    op.drop_column('valla', 'register_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('valla', sa.Column('register_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('valla', 'created')
    op.drop_column('valla', 'format')
    op.drop_column('user', 'created')
    op.drop_column('owner', 'created')
    op.add_column('order', sa.Column('register_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('order', 'created')
    op.drop_column('client', 'created')
    # ### end Alembic commands ###
