"""empty message

Revision ID: ef2dd074a24f
Revises: 53cb008e1a00
Create Date: 2022-04-08 15:40:39.338672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef2dd074a24f'
down_revision = '53cb008e1a00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('valla', sa.Column('ligth', sa.Boolean(), nullable=True))
    op.alter_column('valla', 'type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('valla', 'type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('valla', 'ligth')
    # ### end Alembic commands ###
