"""empty message

Revision ID: f16f3de08d71
Revises: ce3374979b2b
Create Date: 2022-03-23 13:30:44.292564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f16f3de08d71'
down_revision = 'ce3374979b2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('site_id', sa.Integer(), nullable=False))
    op.add_column('site', sa.Column('site_code', sa.String(length=10), nullable=False))
    op.add_column('site', sa.Column('owner_name', sa.String(length=150), nullable=False))
    op.add_column('site', sa.Column('client_name', sa.String(length=150), nullable=True))
    op.drop_constraint('site_code_key', 'site', type_='unique')
    op.create_unique_constraint(None, 'site', ['site_code'])
    op.drop_column('site', 'code')
    op.drop_column('site', 'id')
    op.drop_column('site', 'owner')
    op.drop_column('site', 'client')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('client', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('site', sa.Column('owner', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.add_column('site', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('site', sa.Column('code', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'site', type_='unique')
    op.create_unique_constraint('site_code_key', 'site', ['code'])
    op.drop_column('site', 'client_name')
    op.drop_column('site', 'owner_name')
    op.drop_column('site', 'site_code')
    op.drop_column('site', 'site_id')
    # ### end Alembic commands ###
